# Generated by Django 5.0.6 on 2026-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=2048)),
                ('indicator_type', models.CharField(choices=[('IP', 'IP'), ('DOMAIN', 'DOMAIN'), ('URL', 'URL'), ('HASH', 'HASH')], max_length=10)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('vt_positives', models.IntegerField(blank=True, null=True)),
                ('vt_total', models.IntegerField(blank=True, null=True)),
                ('abuse_confidence_score', models.IntegerField(blank=True, null=True)),
                ('abuse_total_reports', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='LOW', max_length=10)),
                ('raw_vt', models.JSONField(blank=True, null=True)),
                ('raw_abuse', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
