# Generated by Django 5.0.6 on 2026-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_threatreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatreport',
            name='raw_urlhaus',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
