# Generated by Django 5.0.6 on 2026-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0003_threatreport_raw_urlhaus'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatreport',
            name='raw_shodan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
