# Generated by Django 5.0.6 on 2026-05-06 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=500)),
                ('indicator_type', models.CharField(choices=[('DOMAIN', 'DOMAIN'), ('IP', 'IP'), ('URL', 'URL')], max_length=10)),
                ('last_risk_level', models.CharField(blank=True, max_length=20)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('alert_on_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'indicator')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_risk', models.CharField(max_length=20)),
                ('new_risk', models.CharField(max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='watchlist.watchlistentry')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
