# Generated by Django 5.0.6 on 2026-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=512)),
                ('reply_to', models.CharField(blank=True, max_length=512, null=True)),
                ('return_path', models.CharField(blank=True, max_length=512, null=True)),
                ('spf_result', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('neutral', 'neutral'), ('none', 'none')], default='none', max_length=10)),
                ('dkim_result', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('neutral', 'neutral'), ('none', 'none')], default='none', max_length=10)),
                ('dmarc_result', models.CharField(choices=[('pass', 'pass'), ('fail', 'fail'), ('neutral', 'neutral'), ('none', 'none')], default='none', max_length=10)),
                ('x_mailer', models.CharField(blank=True, max_length=255, null=True)),
                ('hop_count', models.IntegerField(default=0)),
                ('suspicious_flags', models.JSONField(default=list)),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=10)),
            ],
        ),
    ]
