# Generated by Django 5.0.6 on 2026-05-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file_name', models.CharField(max_length=255)),
                ('total_urls', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], default='QUEUED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL'), ('ERROR', 'ERROR')], default='LOW', max_length=10)),
                ('vt_positives', models.IntegerField(blank=True, null=True)),
                ('gsb_flagged', models.BooleanField(blank=True, null=True)),
                ('abuse_confidence', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('bulk_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='bulk_scanner.bulkscan')),
            ],
        ),
    ]
