# Generated by Django 5.0.6 on 2026-05-06 13:24

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vt_api_key', accounts.models.EncryptedCharField(blank=True, default='')),
                ('abuseipdb_key', accounts.models.EncryptedCharField(blank=True, default='')),
                ('gsb_api_key', accounts.models.EncryptedCharField(blank=True, default='')),
                ('news_api_key', accounts.models.EncryptedCharField(blank=True, default='')),
                ('personal_api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
