# Generated by Django 5.0.6 on 2026-05-06 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_label', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total_urls', models.IntegerField(default=0)),
                ('total_campaigns', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='URLRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_url', models.URLField(max_length=500)),
                ('domain', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('subnet', models.CharField(blank=True, max_length=20, null=True)),
                ('hosting_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords_found', models.JSONField(default=list)),
                ('structural_fingerprint', models.JSONField(default=list)),
                ('entropy_score', models.FloatField(blank=True, null=True)),
                ('suspicion_score', models.FloatField(blank=True, null=True)),
                ('suspicion_label', models.CharField(blank=True, max_length=20, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_records', to='correlation.campaignscan')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_index', models.IntegerField()),
                ('url_count', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('confidence_label', models.CharField(max_length=20)),
                ('shared_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('shared_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('reasons', models.JSONField(default=list)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='correlation.campaignscan')),
                ('urls', models.ManyToManyField(blank=True, to='correlation.urlrecord')),
            ],
        ),
    ]
