# Generated by Django 5.0.6 on 2026-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=255)),
                ('vt_positives', models.IntegerField(default=0)),
                ('vt_total', models.IntegerField(default=0)),
                ('gsb_flagged', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='LOW', max_length=10)),
                ('whois_registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('raw_vt_response', models.JSONField(default=dict)),
                ('raw_gsb_response', models.JSONField(default=dict)),
            ],
        ),
    ]
