# Generated by Django 5.0.6 on 2026-05-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='screenshot_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
