# Generated by Django 5.0.6 on 2026-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanresult_screenshot_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='phishtank_flagged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='raw_phishtank',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
