# Generated by Django 5.0.6 on 2026-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scanresult_phishtank_flagged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='raw_ssl',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
